version: "3.7"
    services:
      client:
        build:
          context: .
          target: development
        environment:
          - NODE_ENV=development
        image: fxethers-client
        container_name: client
        ports:
          - "3000:80" # map 80 in container => 3000 in local

# docker build --target development -t fxethers-client .