name: deploy-react-client

run-name: Deploy to production by @${{ github.actor }}

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: 'client'
    steps:
    - uses: actions/checkout@deployment
    - name: Use Node.js 16.18.1
      uses: actions/setup-node@deployment
      with:
        node-version: '16.18.1'
        cache: 'npm'
        cache-dependency-path: './client/package-lock.json'
    - name: Install dependencies
      run: npm install
    - name: Build and test the apps
      run: |
        npm run build
        CI=true npm test
    - name: Deploy NodeJS app
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
        key: ${{secrets.SSH_PRIVATE_KEY}} # Private or public key of the server
        username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
        script: |
          cd nft
          git pull
          pm2 reload all
          echo 'Deployment successful to VPS'